import unittest

from src.Factory.CreatorElectionDistrictFirstRound import CreatorElectionDistrictFirstRound

#TODO complete unit test
#TODO factorize
#TODO factorize this assert part
class CreatorFirstRoundDataTest(unittest.TestCase) : 
    def test_creator_election_district_first_round_first_line(self):
        creator = CreatorElectionDistrictFirstRound()
            
        first_round_data = creator.factory_method("['01' 'Ain' 1 '1ère circonscription' 'Complet' 86187 43652 '50.65' 42535 '49.35' 490 '0.57' '1.15' 234 '0.27' '0.55' 41811 '48.51' '98.3' 2 'M' 'LAHY' 'Éric' 'DXG' 391 '0.45' '0.94' 'nan' 8 'M' 'GUÉRAUD' 'Sébastien' 'NUP' 9982 '11.58' '23.87' 'nan' 7 'F' 'ARMENJON' 'Eliane' 'ECO' 1161 '1.35' '2.78' 'nan' 1 'M' 'GUILLERMIN' 'Vincent' 'ENS' 8071 '9.36' '19.3' 'nan' '3.0' 'M' 'BRETON' 'Xavier' 'LR' '10599.0' '12.3' '25.35' 'nan' '5.0' 'M' 'MENDES' 'Michael' 'DSV' '641.0' '0.74' '1.53' 'nan' '6.0' 'M' 'BELLON' 'Julien' 'REC' '1995.0' '2.31' '4.77' 'nan' '4.0' 'F' 'PIROUX GIANNOTTI' 'Brigitte' 'RN' '8971.0' '10.41' '21.46' 'nan' 'nan']")
            
        self.assertTrue(first_round_data.department != None)
        self.assertEqual(1, first_round_data.department.number)
        self.assertEqual('Ain', first_round_data.department.name)
        self.assertTrue(first_round_data.district != None)
        self.assertEqual(1, first_round_data.district.number)
        self.assertEqual('1ère circonscription', first_round_data.district.name)
        self.assertEqual('Complet', first_round_data.election.state_compute)
        self.assertEqual(86187, first_round_data.election.registered)
        self.assertEqual(43652, first_round_data.election.abstaining)
        self.assertEqual(50.65, first_round_data.election.rate_abstaining)
        self.assertEqual(42535, first_round_data.election.voting)
        self.assertEqual(49.35, first_round_data.election.rate_voting)  
        self.assertEqual(490, first_round_data.election.blank_balot)    
        self.assertEqual(0.57, first_round_data.election.rate_blank_registered)   
        self.assertEqual(1.15, first_round_data.election.rate_blank_voting)       
        self.assertEqual(234, first_round_data.election.null_ballot)  
        self.assertEqual(0.27, first_round_data.election.rate_null_registered)  
        self.assertEqual(0.55, first_round_data.election.rate_null_voting)  
        self.assertEqual(41811, first_round_data.election.expressed)  
        self.assertEqual(48.51, first_round_data.election.rate_express_registered)  
        self.assertEqual(98.3, first_round_data.election.rate_express_voting)  
        self.assertEqual(8, len(first_round_data.candidates))
        self.assertEqual('M', first_round_data.candidates[0].sexe)
        self.assertEqual('LAHY', first_round_data.candidates[0].last_name)
        self.assertEqual('Éric', first_round_data.candidates[0].first_name)
        self.assertEqual(391, first_round_data.candidates[0].vote)
        self.assertEqual(0.45, first_round_data.candidates[0].rate_vote_registered)
        self.assertEqual(0.94, first_round_data.candidates[0].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[1].sexe)
        self.assertEqual('GUÉRAUD', first_round_data.candidates[1].last_name)
        self.assertEqual('Sébastien', first_round_data.candidates[1].first_name)
        self.assertEqual(9982, first_round_data.candidates[1].vote)
        self.assertEqual(11.58, first_round_data.candidates[1].rate_vote_registered)
        self.assertEqual(23.87, first_round_data.candidates[1].rate_vote_expressed)
        self.assertEqual('F', first_round_data.candidates[2].sexe)
        self.assertEqual('ARMENJON', first_round_data.candidates[2].last_name)
        self.assertEqual('Eliane', first_round_data.candidates[2].first_name)
        self.assertEqual(1161, first_round_data.candidates[2].vote)
        self.assertEqual(1.35, first_round_data.candidates[2].rate_vote_registered)
        self.assertEqual(2.78, first_round_data.candidates[2].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[3].sexe)
        self.assertEqual('GUILLERMIN', first_round_data.candidates[3].last_name)
        self.assertEqual('Vincent', first_round_data.candidates[3].first_name)
        self.assertEqual(8071, first_round_data.candidates[3].vote)
        self.assertEqual(9.36, first_round_data.candidates[3].rate_vote_registered)
        self.assertEqual(19.3, first_round_data.candidates[3].rate_vote_expressed)        
        self.assertEqual('M', first_round_data.candidates[4].sexe)
        self.assertEqual('BRETON', first_round_data.candidates[4].last_name)
        self.assertEqual('Xavier', first_round_data.candidates[4].first_name)
        self.assertEqual(10599, first_round_data.candidates[4].vote)
        self.assertEqual(12.3, first_round_data.candidates[4].rate_vote_registered)
        self.assertEqual(25.35, first_round_data.candidates[4].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[5].sexe)
        self.assertEqual('MENDES', first_round_data.candidates[5].last_name)
        self.assertEqual('Michael', first_round_data.candidates[5].first_name)
        self.assertEqual(641, first_round_data.candidates[5].vote)
        self.assertEqual(0.74, first_round_data.candidates[5].rate_vote_registered)
        self.assertEqual(1.53, first_round_data.candidates[5].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[6].sexe)
        self.assertEqual('BELLON', first_round_data.candidates[6].last_name)
        self.assertEqual('Julien', first_round_data.candidates[6].first_name)
        self.assertEqual(1995, first_round_data.candidates[6].vote)
        self.assertEqual(2.31, first_round_data.candidates[6].rate_vote_registered)
        self.assertEqual(4.77, first_round_data.candidates[6].rate_vote_expressed)
        self.assertEqual('F', first_round_data.candidates[7].sexe)
        self.assertEqual('PIROUX GIANNOTTI', first_round_data.candidates[7].last_name)
        self.assertEqual('Brigitte', first_round_data.candidates[7].first_name)
        self.assertEqual(8971, first_round_data.candidates[7].vote)
        self.assertEqual(10.41, first_round_data.candidates[7].rate_vote_registered)
        self.assertEqual(21.46, first_round_data.candidates[7].rate_vote_expressed)
        
        
    def test_creator_election_district_first_round_one_hundred_and_first_line(self):
        creator = CreatorElectionDistrictFirstRound()
            
        first_round_data = creator.factory_method("['25' 'Doubs' 2 '2ème circonscription' 'Complet' 79162 37688 '47.61' 41474 '52.39' 821 '1.04' '1.98' 326 '0.41' '0.79' 40327 '50.94' '97.23' 8 'F' 'VUITTON' 'Brigitte' 'DXG' 779 '0.98' '1.93' 'nan' 2 'M' 'RAVACLEY' 'Stéphane' 'NUP' 13112 '16.56' '32.51' 'nan' 6 'M' 'THOMASSIN' 'Geoffrey' 'DIV' 216 '0.27' '0.54' 'nan' 4 'F' 'MEYER' 'Claudine' 'REG' 0 '0.0' '0.0' 'nan' '3.0' 'M' 'ALAUZET' 'Eric' 'ENS' '12647.0' '15.98' '31.36' 'nan' '1.0' 'F' 'KAOULAL' 'Chafia' 'LR' '4354.0' '5.5' '10.8' 'nan' '7.0' 'M' 'PRENEL' 'Jim' 'DSV' '692.0' '0.87' '1.72' 'nan' '5.0' 'F' 'CARRAU' 'Barbara' 'REC' '1472.0' '1.86' '3.65' 'nan' '9.0' 'M' 'FUSIS' 'Eric' 'RN' '7055.0' '8.91' '17.49' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan' 'nan']")
            
        self.assertTrue(first_round_data.department != None)
        self.assertEqual(25, first_round_data.department.number)
        self.assertEqual('Doubs', first_round_data.department.name)
        self.assertTrue(first_round_data.district != None)
        self.assertEqual(2, first_round_data.district.number)
        self.assertEqual('2ème circonscription', first_round_data.district.name)
        self.assertEqual('Complet', first_round_data.election.state_compute)
        self.assertEqual(79162, first_round_data.election.registered)
        self.assertEqual(37688, first_round_data.election.abstaining)
        self.assertEqual(47.61, first_round_data.election.rate_abstaining)
        self.assertEqual(41474, first_round_data.election.voting)
        self.assertEqual(52.39, first_round_data.election.rate_voting)  
        self.assertEqual(821, first_round_data.election.blank_balot)    
        self.assertEqual(1.04, first_round_data.election.rate_blank_registered)   
        self.assertEqual(1.98, first_round_data.election.rate_blank_voting)       
        self.assertEqual(326, first_round_data.election.null_ballot)  
        self.assertEqual(0.41, first_round_data.election.rate_null_registered)  
        self.assertEqual(0.79, first_round_data.election.rate_null_voting)  
        self.assertEqual(40327, first_round_data.election.expressed)  
        self.assertEqual(50.94, first_round_data.election.rate_express_registered)  
        self.assertEqual(97.23, first_round_data.election.rate_express_voting)  
        self.assertEqual(9, len(first_round_data.candidates))
        self.assertEqual('F', first_round_data.candidates[0].sexe)
        self.assertEqual('VUITTON', first_round_data.candidates[0].last_name)
        self.assertEqual('Brigitte', first_round_data.candidates[0].first_name)
        self.assertEqual(779, first_round_data.candidates[0].vote)
        self.assertEqual(0.98, first_round_data.candidates[0].rate_vote_registered)
        self.assertEqual(1.93, first_round_data.candidates[0].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[1].sexe)
        self.assertEqual('RAVACLEY', first_round_data.candidates[1].last_name)
        self.assertEqual('Stéphane', first_round_data.candidates[1].first_name)
        self.assertEqual(13112, first_round_data.candidates[1].vote)
        self.assertEqual(16.56, first_round_data.candidates[1].rate_vote_registered)
        self.assertEqual(32.51, first_round_data.candidates[1].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[2].sexe)
        self.assertEqual('THOMASSIN', first_round_data.candidates[2].last_name)
        self.assertEqual('Geoffrey', first_round_data.candidates[2].first_name)
        self.assertEqual(216, first_round_data.candidates[2].vote)
        self.assertEqual(0.27, first_round_data.candidates[2].rate_vote_registered)
        self.assertEqual(0.54, first_round_data.candidates[2].rate_vote_expressed)
        self.assertEqual('F', first_round_data.candidates[3].sexe)
        self.assertEqual('MEYER', first_round_data.candidates[3].last_name)
        self.assertEqual('Claudine', first_round_data.candidates[3].first_name)
        self.assertEqual(0, first_round_data.candidates[3].vote)
        self.assertEqual(0.0, first_round_data.candidates[3].rate_vote_registered)
        self.assertEqual(0.0, first_round_data.candidates[3].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[4].sexe)
        self.assertEqual('ALAUZET', first_round_data.candidates[4].last_name)
        self.assertEqual('Eric', first_round_data.candidates[4].first_name)
        self.assertEqual(12647, first_round_data.candidates[4].vote)
        self.assertEqual(15.98, first_round_data.candidates[4].rate_vote_registered)
        self.assertEqual(31.36, first_round_data.candidates[4].rate_vote_expressed)
        self.assertEqual('F', first_round_data.candidates[5].sexe)
        self.assertEqual('KAOULAL', first_round_data.candidates[5].last_name)
        self.assertEqual('Chafia', first_round_data.candidates[5].first_name)
        self.assertEqual(4354, first_round_data.candidates[5].vote)
        self.assertEqual(5.5, first_round_data.candidates[5].rate_vote_registered)
        self.assertEqual(10.8, first_round_data.candidates[5].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[6].sexe)
        self.assertEqual('PRENEL', first_round_data.candidates[6].last_name)
        self.assertEqual('Jim', first_round_data.candidates[6].first_name)
        self.assertEqual(692, first_round_data.candidates[6].vote)
        self.assertEqual(0.87, first_round_data.candidates[6].rate_vote_registered)
        self.assertEqual(1.72, first_round_data.candidates[6].rate_vote_expressed)
        self.assertEqual('F', first_round_data.candidates[7].sexe)
        self.assertEqual('CARRAU', first_round_data.candidates[7].last_name)
        self.assertEqual('Barbara', first_round_data.candidates[7].first_name)
        self.assertEqual(1472, first_round_data.candidates[7].vote)
        self.assertEqual(1.86, first_round_data.candidates[7].rate_vote_registered)
        self.assertEqual(3.65, first_round_data.candidates[7].rate_vote_expressed)
        self.assertEqual('M', first_round_data.candidates[8].sexe)
        self.assertEqual('FUSIS', first_round_data.candidates[8].last_name)
        self.assertEqual('Eric', first_round_data.candidates[8].first_name)
        self.assertEqual(7055, first_round_data.candidates[8].vote)
        self.assertEqual(8.91, first_round_data.candidates[8].rate_vote_registered)
        self.assertEqual(17.49, first_round_data.candidates[8].rate_vote_expressed)
        